version: '3'

services:
  php:
    container_name: symfony-php
    hostname: symfony-php
    build: .
    restart: unless-stopped
    depends_on: 
      - mysql
    ports:
      - 8888:80
    volumes:
      - ./:/app
    networks:
      - bridge

  mysql:
    container_name: symfony-mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - data_mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - bridge

  phpmyadmin:
    container_name: symfony-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8889:80
    environment:
      - PMA_HOST=mysql
    networks:
      - bridge

networks:
  bridge:

volumes:
  data_mysql: